### ISSUE TITLE
Update thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/try-manubot#7]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![New Project](https://user-images.githubusercontent.com/8326331/64821582-2b920c80-d581-11e9-8e5f-cd4d17e80580.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by dhimmel** [comment]
Nice logo. @vincerubinetti, you want to go ahead and make the PR. I think you can do it from the upload files github web interface

**Comment by vincerubinetti** [comment]
Doesn't seem I have access to commit directly to master with the GUI.

I can do a PR but isn't this one supposed to be sorta dirty.  
![image](https://user-images.githubusercontent.com/8326331/64869607-aefa3f00-d60f-11e9-93c4-372ac71fdbe2.png)

**Comment by dhimmel** [comment]
We'd like try-manubot to be dirty but also PR based to demonstrate the PR workflow.

**Comment by agitter** [comment]
@vincerubinetti if you haven't already made issues for other manuscripts in the catalog, you could switch to PRs generally.  That way the maintainer only needs to approve and merge if they like your thumbnail.  It also ensures the image ends up in the root of the repository.

Great logo.

**Comment by vincerubinetti** [comment]
That would've been significantly more time, as I was doing this for like 20 manuscripts. Would've given me 20 forks in my username that I'd have to keep until they were resolved, which I don't want, either.

This is only a one time thing anyway. After this, people are on their own  for making their thumbs. I'll do this one though.

**Comment by vincerubinetti** [comment]
Closed by #8
